version: '{build}'

image:
  - Visual Studio 2013

configuration:
  - Release

install:
  - git submodule update --init --recursive

build:
  project: src\wave-packet\wave-packet.sln

artifacts:
  - path: 'src\wave-packet\%CONFIGURATION%\wave-packet.exe'
